version: "3.7"

services: 
  database:
    image: postgres:12-alpine
    container_name: reddit-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin-reddit
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  redis:
    image: redis
    container_name: reddit-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data/

volumes:
  postgres:
  redis: