// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreatePost struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type LoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Post struct {
	ID          int       `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type RegisterUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UpdatePost struct {
	ID          int     `json:"id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
}

type User struct {
	ID        int       `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
