// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangePassword struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type CreatePost struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type LoginUser struct {
	UsernameOrEmail string `json:"usernameOrEmail"`
	Password        string `json:"password"`
}

type RegisterUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdatePost struct {
	ID      int     `json:"id"`
	Title   *string `json:"title"`
	Content *string `json:"content"`
}
