// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Post struct {
	ID        int64
	Owner     int64
	Title     string
	Content   string
	Upvotes   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Upvote struct {
	UserId    int64
	PostId    int64
	Value     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
