// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Post struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	Createdat time.Time `json:"createdat"`
	Updatedat time.Time `json:"updatedat"`
}
