// Code generated by sqlc. DO NOT EDIT.
// source: post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO post (
  title
) VALUES (
  $1
) RETURNING id, title, createdat, updatedat
`

func (q *Queries) CreatePost(ctx context.Context, title string) (Post, error) {
	row := q.queryRow(ctx, q.createPostStmt, createPost, title)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
