// Code generated by sqlc. DO NOT EDIT.
// source: upvote.sql

package db

import (
	"context"
)

const createUpvote = `-- name: CreateUpvote :one
INSERT INTO upvotes (
    "userId", 
    "postId", 
    value
) VALUES (
    $1, $2, $3
) RETURNING "userId", "postId", value, created_at, updated_at
`

type CreateUpvoteParams struct {
	UserId int64
	PostId int64
	Value  int32
}

func (q *Queries) CreateUpvote(ctx context.Context, arg CreateUpvoteParams) (Upvote, error) {
	row := q.queryRow(ctx, q.createUpvoteStmt, createUpvote, arg.UserId, arg.PostId, arg.Value)
	var i Upvote
	err := row.Scan(
		&i.UserId,
		&i.PostId,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
