// Code generated by sqlc. DO NOT EDIT.
// source: upvote.sql

package db

import (
	"context"
)

const createUpvote = `-- name: CreateUpvote :one
INSERT INTO upvotes (
    "userId", 
    "postId", 
    value
) VALUES (
    $1, $2, $3
) RETURNING "userId", "postId", value, created_at, updated_at
`

type CreateUpvoteParams struct {
	UserId int64
	PostId int64
	Value  int32
}

func (q *Queries) CreateUpvote(ctx context.Context, arg CreateUpvoteParams) (Upvote, error) {
	row := q.queryRow(ctx, q.createUpvoteStmt, createUpvote, arg.UserId, arg.PostId, arg.Value)
	var i Upvote
	err := row.Scan(
		&i.UserId,
		&i.PostId,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpvote = `-- name: GetUpvote :one
SELECT "userId", "postId", value, created_at, updated_at FROM upvotes WHERE "userId" = $1 AND "postId" = $2 LIMIT 1
`

type GetUpvoteParams struct {
	UserId int64
	PostId int64
}

func (q *Queries) GetUpvote(ctx context.Context, arg GetUpvoteParams) (Upvote, error) {
	row := q.queryRow(ctx, q.getUpvoteStmt, getUpvote, arg.UserId, arg.PostId)
	var i Upvote
	err := row.Scan(
		&i.UserId,
		&i.PostId,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUpvote = `-- name: UpdateUpvote :exec
UPDATE upvotes SET value = $3 WHERE "userId" = $1 AND "postId" = $2
`

type UpdateUpvoteParams struct {
	UserId int64
	PostId int64
	Value  int32
}

func (q *Queries) UpdateUpvote(ctx context.Context, arg UpdateUpvoteParams) error {
	_, err := q.exec(ctx, q.updateUpvoteStmt, updateUpvote, arg.UserId, arg.PostId, arg.Value)
	return err
}
